//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class userr
    {
        public int userr_id { get; set; }
        public string userr_name { get; set; }
        public string userr_pass { get; set; }
        public Nullable<int> userr_age { get; set; }
        public string userr_gender { get; set; }
        public string userr_phone { get; set; }
        public string userr_city { get; set; }
    }
}
